"""Task 8b authored browser-only operator/docs/Guide requirements.

Development-first policy: source checks only; not executed until Phase 3.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def text(path: str) -> str:
    return (ROOT / path).read_text(encoding='utf-8')


def assert_browser_preflight(source: str) -> None:
    assert 'browser_session_ready' in source
    assert 'backend_ready' in source
    assert 'authentication' in source
    assert 'lease_held' in source
    assert 'extension_connected' not in source
    assert 'flow_key_present' not in source
    assert 'NO_FLOW_KEY' not in source
    assert 'localhost:9222' not in source
    assert '127.0.0.1:9222' not in source


def test_generated_agents_source_is_browser_only():
    source = text('setup.py')
    assert_browser_preflight(source)
    assert 'Chrome-extension/WebSocket Flow transport' not in source
    assert 'Do not delete the extension early' not in source
    assert 'extension backend' not in source
    assert 'persistent signed-in Flow browser profile' in source


def test_checked_in_agents_and_claude_preflight_are_browser_only():
    assert_browser_preflight(text('AGENTS.md'))
    assert_browser_preflight(text('CLAUDE.md'))


def test_readme_current_operator_sections_are_browser_only():
    source = text('README.md')
    current = source.split('## Historical migration notes', 1)[0]
    assert_browser_preflight(current)
    assert 'Load Chrome extension' not in current
    assert 'Chrome Extension — Live Dashboard' not in current
    assert 'extension/' not in current
    assert 'WebSocket bridge to the extension' not in current
    assert 'persistent browser profile' in current.lower()


def test_dashboard_guide_uses_browser_health_and_keeps_dashboard_ws_separate():
    guide = text('dashboard/src/pages/GuidePage.tsx')
    assert 'browser_session_ready' in guide
    assert 'reconciliation_required' in guide
    assert 'paid_dispatch_enabled' in guide
    assert 'extension_connected' not in guide
    assert '.ws.' not in guide


def test_i18n_operator_copy_has_no_flow_extension_setup_instructions():
    source = text('dashboard/src/i18n/translations.ts')
    forbidden = (
        'Chrome Extension Setup Guide',
        'chrome://extensions',
        'Load unpacked',
        'extension_connected',
        'NO_FLOW_KEY',
        'port 9222',
        'cổng 9222',
        'extension/ folder',
        'extension/ फ़ोल्डर',
    )
    for marker in forbidden:
        assert marker not in source
    assert "'guide.status.browserReady'" in source
    assert "'guide.status.paidLocked'" in source
    assert "'guide.status.dashboardChannel'" in source


def test_core_operator_skills_use_browser_session_diagnostics():
    for path in (
        'skills/fk-doctor.md',
        'skills/fk-dashboard.md',
        'skills/fk-status.md',
        'skills/fk-pipeline.md',
    ):
        source = text(path)
        assert 'extension_connected' not in source
        assert 'reload extension' not in source.lower()
    doctor = text('skills/fk-doctor.md')
    assert 'RECONCILIATION_REQUIRED' in doctor
    assert 'BROWSER_NOT_READY' in doctor
    assert 'PROFILE_' in doctor


def test_docs_forbid_profile_cookie_or_storage_reset_instead_of_prescribing_it():
    paths = (
        'setup.py', 'AGENTS.md', 'CLAUDE.md', 'README.md',
        'dashboard/src/i18n/translations.ts', 'skills/fk-doctor.md',
    )
    combined = '\n'.join(text(path) for path in paths).lower()

    # Old recovery recipes actively prescribed destructive profile mutation.
    for marker in (
        'remove all cookies',
        'delete cookies for',
        'clear cookies for',
        'clear browser storage and',
        'create a new profile and',
    ):
        assert marker not in combined

    # Current operator guidance explicitly preserves the bound profile.
    assert 'do not clear cookies/storage' in combined or 'never clear cookies/storage' in combined
    assert 'replacement profile' in combined


def test_statusline_reads_browser_health_not_extension_or_flow_key():
    source = text('scripts/statusline.sh')
    assert 'browser_session_ready' in source
    assert 'backend_ready' in source
    assert 'reconciliation_required' in source
    assert 'paid_dispatch_enabled' in source
    assert 'extension_connected' not in source
    assert 'flow_key_present' not in source
    assert '.ws.' not in source


def test_changed_claude_command_artifacts_are_stubs_over_current_skills():
    for name in ('doctor', 'dashboard', 'status', 'pipeline'):
        source = text(f'.claude/commands/fk-{name}.md')
        assert '<!-- AUTO-GENERATED by setup.py' in source
        assert f'Read and follow the instructions in skills/fk-{name}.md' in source
        assert 'extension_connected' not in source
        assert 'reload extension' not in source.lower()


def test_architecture_and_capture_docs_are_browser_only():
    architecture = text('ARCHITECTURE.md')
    capture = text('docs/CAPTURE.md')
    omni = text('docs/OMNI_FLASH.md')
    authority = text('docs/comicreels/FLOW-BROWSER-FIRST-ARCHITECTURE.md')

    assert 'BrowserFlowBackend' in architecture
    assert 'extension/background.js' not in capture
    assert 'extension_connected' not in omni
    assert 'Chrome extension is disconnected' not in omni
    assert 'extension transport may implement' not in authority
    assert 'retained | removable only after FBR-5' not in authority


def test_legacy_plan_is_explicitly_historical_not_operator_authority():
    plan = text('PLAN.md')
    assert plan.startswith('# HISTORICAL / SUPERSEDED')
    assert '2026-10-01-flow-browser-only-cutover.md' in plan


def test_additional_flow_skills_drop_extension_preflight():
    for path in (
        'skills/fk-gen-refs.md',
        'skills/fk-monitor.md',
        'skills/fk-refresh-urls.md',
    ):
        source = text(path)
        assert 'extension_connected' not in source
        assert 'flow_key_present' not in source
        assert 'Extension not connected' not in source
        assert 'NO_FLOW_TAB' not in source
        assert 'browser' in source.lower()


def test_review_and_upload_skills_use_browser_preflight():
    for path in ('skills/fk-review-video.md', 'skills/fk-upload-image.md'):
        source = text(path)
        assert 'extension_connected' not in source
        assert 'flow_key_present' not in source
        assert "Chrome extension's" not in source
        assert 'browser' in source.lower()


def test_all_generated_claude_flow_commands_have_no_stale_extension_preflight():
    commands = ROOT / '.claude' / 'commands'
    forbidden = (
        'extension_connected',
        'flow_key_present',
        'NO_FLOW_KEY',
        'NO_FLOW_TAB',
        'Extension not connected',
        'reload extension',
        'chrome://extensions',
        '127.0.0.1:9222',
    )
    for path in commands.glob('fk-*.md'):
        source = path.read_text(encoding='utf-8')
        for marker in forbidden:
            assert marker not in source, f'{path.name}: {marker}'


def test_current_vision_names_browser_only_flow_foundation():
    vision = text('docs/comicreels/VISION.md')
    assert 'FastAPI/React/Chrome Extension' not in vision
    assert 'browser-only' in vision.lower()


def test_segment1_architecture_is_marked_superseded_without_rewriting_history():
    architecture = text('docs/comicreels/ARCHITECTURE.md')
    assert 'HISTORICAL / SUPERSEDED' in architecture.splitlines()[0]
    assert 'FLOW-BROWSER-FIRST-ARCHITECTURE.md' in architecture
